### ISSUE TITLE
[P0] Routing with react-router-dom for all pages

### ISSUE THREAD

**Issue by seiwonpark** [kookmin-sw/capstone-2023-40#12]
**(Edited)**

No other features but only paginations.

**Page List (Whatever route names)**:

- `/` : Landing page
- `/login` : Login page
- `/register` : Register page
- `/survey` : SurveyList page
- `/survey/:id` : Survey page (survey participant) with id `:id`
- `/survey/form` : Survey form page (survey owner)
- `/survey/login-required` : Sign in required survey popup page
- `/mypage` : User's profile page with **session data**
- `/mypage/auth-list` : User's authenticated list page with **session data**
- `/mypage/survey-result` or `/mypage/survey-result/:id` : Survey result page (with id `:id`)

**Comment by seiwonpark** [comment]
`/mypage/:id` : User's profile page with id :id is **NOT** appropriate at all.

**Comment by sanghyun1128** [comment]
I understood that we'll use :id only for classify 'Survey', not 'User'. Is it correct?

**Comment by seiwonpark** [comment]
Yes. Classifying user should be done by session. But surveys don't have to be.
