### ISSUE TITLE
[P0] 사용자의 인증 정보를 저장한다면, 언제까지 보관해야 할까요?

### ISSUE THREAD

**Issue by bezzang-dev** [kookmin-sw/capstone-2023-40#147]
우리 서비스는 사용자가 어떤 인증을 하였는가 에 대한 정보를 데이터베이스에 저장하도록 설계하였습니다.
그렇다면 이 _**인증 정보를 언제까지 보관해야 하는가**_ 에 대한 의문이 생겼습니다.
사실 인증 정보라 해 봤자 인증을 받았는가 안 받았는가 뿐이긴 합니다.

카카오 인증서의 경우, 
카카오 인증서 만료 기한은 3년으로 명시 되어있습니다.
그 이후로는 다시 인증을 받아서 갱신을 해주어야 합니다.
**카카오 인증서 만료 기한 안내**
https://cs.kakao.com/helps?articleId=1073203266&service=179&category=660&device=2520&locale=ko

애초에 왜 인증 만료 기한이 필요할까요??
**WHY IS CERTIFICATE EXPIRATION NECESSARY?**
https://www.entrust.com/blog/2016/10/why-is-certificate-expiration-necessary/

위 사이트에선 보안 기술의 발전 (새로운 알고리즘 및 프로토콜)과 보안 취약점이 개선되면서 인증서를 관리하는 방법도 변경되고 있기 때문에,
인증서의 대한 만료 기한과 갱신이 필요하다고 말합니다. 
그런데 우리 서비스에선 어떠한 인증서를 저장하지 않고 설문조사 참여를 위해 인증을 했는가 안 했는가 여부만 저장하고 있어 해당 사항이 없는 이야기라고 생각합니다.

또한 사용자의 계정이 해킹되었다고 가정해 보면,
해커는 사용자의 이미 인증된 정보를 통해 원하는대로 설문조사를 참여할 수 있게 됩니다. 
이는 우리 서비스의 장점인 '**설문조사 결과에 대한 신뢰성**'에 어긋나게 됩니다.
**근데 사실 이 상황이 발생하려면 계정이 해킹되었을때 상황이고, 계정과 개인 정보의 보안을 강화해야하지
인증의 만료 기한과는 아무 상관이 없는 것 같습니다.**

처음에는 다른 인증 업체가 인증 만료 기한을 설정하고 있으니, 우리도 필요하다고 생각했었는데
고민해 보니 우리 서비스에서 인증 만료 기한 설정은 필요 없는 것 같습니다.
오히려 개인 정보를 얼마나 보관할 것 인가, ~~휴먼~~ 휴면 계정 설정, 한 번 이상 접속한 네트워크 IP와는 다른 IP 접속과 같은
쪽의 보안을 강화해야 하지 않을까 느꼈습니다.

관련된 이슈로, 개인 정보 저장 기간과 얼마나 로그인 접속이 안되면 휴먼 계정으로 전환해야 하는지도 고민해보아야 할 것 같습니다.
여러분들의 의견이 궁금합니다!

**Comment by seiwonpark** [comment]
<img width="300" alt="Screenshot 2023-05-10 at 3 25 07 PM" src="https://github.com/kookmin-sw/capstone-2023-40/assets/63793178/ac8eb7dc-6e20-4138-83fb-82fb1e7dd6d0">

우선 제가 살아오면서 관련 오타를 정말 많이 봐서 정정드립니다. 휴"면" 계정입니다. 

제 개인적인 생각으로는 "해킹"이라는 상황을 가정하면 사실 모든 서비스의 기능이 무용지물이 될 것이라, 비단 인증 수단만이 문제가 아닐 듯 합니다. 해킹을 당했다고 하면 그땐 정말 법적 조치를 취하는게 옳다고 생각합니다.

그 정도가 아닌, 단순 "인증 정보의 유효기간 설정"과 관련해 말씀을 드리면, 각 인증서별 유효기간을 설정하는 것이 바람직해 보입니다. 여기에는 다음의 이유가 있습니다.
- 사용자의 개인정보 이용 및 수집 동의에는 [개인정보 보호법 제15조](https://www.law.go.kr/%EB%B2%95%EB%A0%B9/%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4%EB%B3%B4%ED%98%B8%EB%B2%95/%EC%A0%9C15%EC%A1%B0)에 따라 "개인정보의 보유 및 이용 기간"을 명시하고 동의를 구해야합니다. 또한, "다음 각 호의 사항을 정보주체에게 알려야 한다. 다음 각 호의 어느 하나의 사항을 변경하는 경우에도 이를 알리고 동의를 받아야 한다."라고 규정 돼 있습니다.
- 다만, [개인정보처리방침](https://jrs.jobkorea.co.kr/suhyup/suhyup23/Main/FooterPopup?Gno=242)에 따라 접속기록, IP주소 등은 통신비밀보호법에 의해 최소 3개월은 보유할 수 있지만, 이후 기간이 지나면 지체없이 파기해야합니다.

**Comment by bezzang-dev** [comment]
오타 정정 감사드립니다! 

제가 사용자의 인증에 관한 정보도 개인 정보의 일부임을 간과하고 있었던 것 같습니다.
@SeiwonPark 님이 말씀하신 것으로 보아, 인증 정보의 만료 기한 설정이 바람직하다고 생각합니다.

그렇다면 각 인증서 별 유효기간을 언제까지 보관해야 하는가가 의문인데,
카카오의 경우 3년, 네이버의 경우 2년의 인증서 만료 기한을 두고 있습니다.
즉 각 인증서 별로 유효 기간을 다르게 저장해야 하는게 바람직하다고 느꼈습니다만,,

직접적으로 알아보는 것보다 인증서에서 만료 일자 정보를 가져올 수 있다면 좋을 것 같은데.. 
이는 한 번 알아보도록 하겠습니다
@ohsung1125 @sanghyun1128 혹시 이에 대해 아시는 부분이 있으면 말씀해주세요!

**Comment by seiwonpark** [comment]
+ 제 개인적인 생각으로는 일관되게 2년으로 정하면 어떨까합니다. 2년이든 3년이든 크리티컬하진 않을 거라고 생각합니다. 기한을 명시하라고 했지 "몇년 이내"와 같은 조건을 보진 못했습니다. 그치만 이건 제 뇌피셜

**Comment by bezzang-dev** [comment]
모든 인증의 만료기한을 2년으로 설정하여 이슈 close 하였습니다.
