### ISSUE TITLE
[P0] Reverting pull request #14

### ISSUE THREAD

**Issue by seiwonpark** [kookmin-sw/capstone-2023-40#15]
You can revert pull request in 2 ways:

1. Manual Revert

    See https://git-scm.com/docs/git-revert.html.
    You can run on your local `develop` branch to revert it.

2. Through Another Pull Request

    You can make another pull request to revert previously merged commit.
    From newly created `revert-14-feature/pagenation` to `develop`.

**Comment by ohsung1125** [comment]
Would you say that i have to revert pull request?

**Comment by seiwonpark** [comment]
@ohsung1125  You've already reverted pull request (#14). But the codes aren't  on `develop` branch. So `develop` branch needs to be updated as well.

As it's been merged by you, reverting PR also lies on you. When you decide to commit/approve, then you have the responsibility on that action.

**Comment by seiwonpark** [comment]
If you have any trouble, please feel free to ask me on slack or on this comment
