### ISSUE TITLE
[P?] `AnsweredQuestionRequestDto` 에서 `certificationTypes`가 필요할까요??

### ISSUE THREAD

**Issue by bezzang-dev** [kookmin-sw/capstone-2023-40#153]
설문조사 응답 제출할 때 사용하는 `AnsweredQuestionRequestDto`에서

`private List<@Valid CertificationType> certificationTypes`가 필요할지 고민입니다.

현재 `UserCertification`에서 사용자의 인증 정보를 저장하는 엔티티 구현하고 있습니다.
그래서 설문조사 응답 제출 시 설문조사의 필요한 `CertificationType`을
`UserCertification`에서 사용자의 인증 목록을 가져온 후, 비교하도록 하였습니다.

그런데 제가 이해한 `certificationTypes` attribute의 역할은 사용자가 인증한 목록을 서버로 보내서
설문조사 참여에 필요한 인증 목록과 비교하기 위함이라 생각했는데 그러면 이 경우엔 certificationTypes의 필요성이 없어보입니다.

혹시 제가 놓치고 있는 다른 필요성이 있을까요??
저 attribute의 역할을 제가 잘못 이해한 것 인지 여쭤보고 싶습니다.

**Comment by seiwonpark** [comment]
`UserCertification`이 어디에 구현 돼 있나요? 제 코드에는 없습니다. 그러니 `createAnswer`를 할 때 `certificationTypes`가 필요하겠죠.

**Comment by bezzang-dev** [comment]
`UserCertification` 구현 완료 후 PR 및 merge까지 끝나면 다시 말씀드리도록 하겠습니다!

**Comment by seiwonpark** [comment]
혼자 가정을 세우고 결론을 만든 뒤, 이미 구현을 시작하는 방식이 마음에 드신다면, 그냥 개인 프로젝트를 하시는 걸 권장드립니다.

이러한 이슈는 일종의 "Suggestion"에 가깝습니다. 이 이슈를 보면서 의도를 파악하긴 했습니다만, 옳지 못한 행동입니다.

1. 의견 교환이나 상의 없이 이미 `UserCertification` 구현 중에 있음. 무슨 코드인지는 공유 안 됨.
2. "내가 만든 `UserCertification`과 상식에 비춰 보아, 설문 응답 시 ~~한 정보를 넘길 필요가 있나?"

저라면 다음과 같이 작성했을 듯 합니다.

```
[P?] AnsweredQuestionRequestDto 에서 certificationTypes가 필요할까요?
---

certificationTypes의 존재이유는 해당 설문에 응답한 사용자의 필수인증 여부를 확인하기 위함입니다.
따라서 해당 사용자의 정보로부터 필수인증 목록을 가져와 비교하는 방식이 논리적으로 옳다고 생각합니다.

즉, 설문응답 시, 필수인증 목록을 클라이언트로부터 제공받을 필요가 없다고 생각합니다. 이에 어떻게 생각하시나요?
```

**Comment by seiwonpark** [comment]
단, 버그와 같은 이슈는 곧바로 수정이 가능할 경우 그냥 수정하시면 됩니다.

**Comment by bezzang-dev** [comment]
세원님 답변을 보고 이슈 내용이 잘못된 것을 파악하였습니다.

아직 존재하지도, 검증되지도 않은 코드에 대해 언급하면서 미래의 예견된 문제를 제기한 것은 옳지 못한 이슈라고 반성하였습니다.

여기서 제가 어디어디 브랜치에 제가 커밋해 놓았는데.. 아니면 PR 했던게 있는데...라면서 확인을 요구했다면 
더 가관이였겠죠...

이슈 내용에 대해 조언 감사드립니다.

**Comment by seiwonpark** [comment]
이번에 인턴을 진행하실 래블업의 김준기 CTO님께서 작성하신 enhancement 이슈([https://github.com/lablup/backend.ai/issues/759](https://github.com/lablup/backend.ai/issues/759))를 참고하시면 좋을 듯 합니다. 많은 걸 배우실 수 있을 듯 합니다.

**Comment by seiwonpark** [comment]
그리고 오픈소스라는 회사의 서비스 특성 상 영어를 사용하실 것 같은데, 올바른 문법을 위해 이슈나 PR을 작성하실 때, 긴 문장이 어려우시다면 번역기를 적극 활용하셨으면 합니다. 잘못 사용된 용어와 표현은 그 분들의 시간만 뺏을 수 있습니다.

**Comment by bezzang-dev** [comment]
네 최대한 영어 소통의 문제가 안생기도록 유의하겠습니다. 이는 확실히 반성하고 있습니다..
