### ISSUE TITLE
[P0] 사용자가 인증이 필요없는 설문조사를 만든다면 `participation` 테이블에 정보를 저장할 수 없습니다.

### ISSUE THREAD

**Issue by bezzang-dev** [kookmin-sw/capstone-2023-40#154]
## 개요
설문조사 생성 요청을 할 때 `certificationTypes`를 빈 리스트로 보내면 `participation`테이블에 아무런 정보가 저장되지 않습니다.

## 시나리오
1. 설문조사 생성 요청을 할 때 `certificationTypes` 값을 빈 리스트로 설정하여 요청합니다.
2. 설문조사 생성 성공 응답이 옵니다.
3. 하지만 db에서 `participation` 테이블엔 아무런 정보가 저장되어 있지 않습니다.

## 원인
`participation` 테이블에서 사용하는 `participationId` 복합키에서 `certificationType`, `userId`, `surveyId`를 사용하고 있습니다.
그런데 사용자가 아무런 인증을 원하지 않는 설문조사를 생성할 경우에, `certificationType` 키로 사용할 값이 없게 됩니다.
키 값은 `null`이 될 수 없기 때문에 결국 아무런 정보를 저장하지 않게 됩니다.

## 해결법
1. 사용자는 설문조사를 생성하려면 **반드시 하나 이상의 인증 방법**을 선택하도록 해야합니다.
2. `participationId`에 `certificationType`을 키로 사용하지 않고, 다른 키 타입을 사용합니다.
3. `certificationType` enum 클래스에서 `None(99)`와 같은 attribute를 추가하여 요청받은 `certificationTypes`가 빈 리스트의 경우엔 인증 타입을 이 attribute로 판단하여 DB에서 사용할 `certificationType` 키 값을 99로 사용하도록 합니다. 

해결법에 대해 다른 아이디어가 있으실까요?? 
제가 인증을 너무 당연히 여기다보니 이 이슈를 늦게 발견한 것 같습니다..

**Comment by seiwonpark** [comment]
> certificationType enum 클래스에서 None(99)와 같은 attribute를 추가하여 요청받은 certificationTypes가 빈 리스트의 경우엔 인증 타입을 이 attribute로 판단하여 DB에서 사용할 certificationType 키 값을 99로 사용하도록 합니다.

방법이 제일 단순해보입니다.

**Comment by bezzang-dev** [comment]
저도 그렇게 생각합니다. 말씀 감사합니다.
