### ISSUE TITLE
[P0] 설문조사 생성에 필요한 포인트와 설문조사 응답 시 보상 포인트는 얼마가 좋을까요??

### ISSUE THREAD

**Issue by bezzang-dev** [kookmin-sw/capstone-2023-40#167]
**"설문조사 생성에 필요한 포인트와 설문조사 응답 시 보상 포인트는 얼마가 좋을까요??"**

질문 이전에, 설문조사 질문 개수에 따른 포인트 차감 또는 보상에 대해 의견을 물어보고 싶습니다.

얼마 전에 지인에게 _"설문조사를 참여해서 커피 기프티콘을 받을 수 있다면, 몇 개나 참여하실래요??"_
란 질문을 했습니다. 그런데 
_"설문조사 하나당 질문이 몇 개 있는데요??"_ 란 답변을 들었습니다.
즉 질문이 많은 설문조사랑 질문이 적은 설문조사랑 대가가 똑같으면 안 할 것 같다는 말을 들었습니다.

그래서 생각한 것은 설문조사 생성 시 질문 10개 당 1포인트를 추가적으로 소모하면 좋을 것 같다는 생각이 들었습니다.
마찬가지로 설문조사를 참여하면 질문 수에 따라 얻는 포인트 양도 달라집니다.

기대 효과는 
1. 사용자는 설문조사 별로 투자한 시간에 따른 적절한 보상을 받을 수 있습니다.

하지만 단점은
1. 설문조사가 급한데 질문이 많은 설문조사 생성을 원하는 사용자는 불만이 생길 수 있습니다.

이 정도라고 생각합니다.

그래서 의견을 구하고자 하는 질문은 
1. 설문조사 질문 개수에 따른 포인트 차감 또는 보상에 대해
2. 설문조사 생성 및 응답 제출 시 몇 포인트를 차감하며 보상해야 하는지 

제 의견은 질문 개수에 따른 차등을 두지 않고 (왜냐하면 일단 서비스가 활성화가 되어야 합니다. 그래서 생성 시에 질문 수 제한을 주면 활성화에 악영향이 될 것 같습니다.)
설문조사 생성과 참여 시 차감, 획득하는 포인트를 1점으로 할까 합니다.
그리고 첫 회원가입 시 기본으로 1 포인트를 부여하려 합니다.

1 포인트가 얼만큼의 현물 가치가 있는가에 대해선 다음 이슈 때 언급하도록 하겠습니다.

**Comment by sanghyun1128** [comment]
1. 설문당 포인트 보다는 질문당 포인트를 정하는건 어떨까요? 
개인적인 생각으로 참여하는 입장에서 설문 하나하나 성실히 응답할 가능성이 높아질것 같습니다
추가로 질문종류에 따라 참여할때 드는 시간이 다르니 가중치를 다르게 보면 좋을 것 같습니다. 
ex) 객관식 : 2pt, 단답형 : 3pt, 주관식 : 5pt
이런식으로 한다면 초기 포인트가 100 정도는 되야 할 것 같습니다.

2. 설문 생성시 드는 포인트가, 한번 참여시 얻는 포인트 보다는 높아야 할것 같습니다. 한 5배...?

3. 번외로 설문당 최대 생성 가능한 질문수와 옵션수는 여유롭게라도 정해 두는 편이 좋을 것 같습니다. 악용할 여지가 있을것 같아요 (혹시 백앤드에서 이미 정해져 있나요?)

**Comment by bezzang-dev** [comment]
@sanghyun1128 좋은 의견 감사드립니다.
각 말씀하신 것에 대해 질문이 있습니다.
1. 좋은 방법이라고 생각합니다! 그런데, "~~~서비스에 불편함을 느끼시는게 있으신가요??" 라는 주관식 답변을 얻기 위해 5포인트를 썼는데
"없습니다"와 같은 답변이 대부분이면 .. 이 부분에 대해선 어떻게 생각하신가요??

2. 5배는 너무 많지 않을까요..? 즉 하나의 설문조사 생성을 위해 5개의 설문을 참여해야 한다면.. 차라리 2-3배는 어떠실까요??

3. 백엔드엔 정해진 것은 없으나, 제한은 둘 수 있습니다. 다만, 프론트에서도 최대 질문 수를 제한하는 것이 가능할까요?? 버튼 비활성화 같은...

**Comment by seiwonpark** [comment]
이슈의 내용 수정바랍니다. 이해가 되질 않습니다.

### 1. 용어 관련
"데드락"이라는 용어를 두 번이나 말씀하셨는데, 이게 제가 아는 데드락과 무슨 관련이 있는지 잘 모르겠습니다. 단순히 "서로 대기하는 교착 상태"라는 용어에 초점을 맞추신 것이 아닌가 합니다. 저희 서비스가 말씀하신 "데드락"을 발생시킨다면, 기획 자체에 문제가 있는 것입니다. 가령, "누가 돈 내고 000을 쓰냐"와 같은 문제입니다. 단순히 빠르게 설문하고 포인트 얻으려는 설문 참여자 vs 하나의 설문으로 많은 포인트를 얻으려는 설문 생성자 라는 구도라면, 이는 수요와 공급의 문제입니다. 비유는 언제나 비유일 뿐, 의견 개진에는 적합하지 않습니다.

<br/>   

### 2. 내용 관련
내용이 이해가 되지 않습니다. 

> 장점1: 사용자가 포인트를 얻기 위해 질문이 적은 설문조사만 참여하려고 하는 행동을 방지할 수 있습니다.
> 장점2: 질문이 많은 설문조사를 응답한 만큼 충분한 보상이 주어지기 때문에 만족감을 느낄 수 있습니다.

> 단점1: 질문이 많은 설문조사 생성을 원하는 사용자들만 존재한다면... 포인트를 벌기 위해 서로 설문조사가 새로 생기기만을 기다리는 상황 발생 (DeadLock)

이게 무슨 말씀인가요? 가령 1000문항 이라는 거대한 설문조사가 있을 경우, "응답한 만큼 충분한 보상이 주어지기 때문에", "질문이 적은 설문조사만 참여하려고 하는 행동을 방지"할 수 있다고 하셨는데, 이것으로 인해, 설문 문항이 적은 설문에 참여하려는 사용자가 적다고 할 수 있을까요? 

진명님의견이

"사용자들이 1000문항 100포인트와 같은 보상이 큰 설문에 참여하려고 대기한다"는 의미라면, 글쎄요.. 사용자마다 다를 것이라 생각합니다. 적어도 저는 제 시간이 돈보다 소중하기 때문에 고작 포인트를 얻기 위해 그런 행동을 하진 않을 것 같습니다. 틈틈이 시간을 내거나, 혹은 제가 설문을 생성하기 위해서 어쩔 수 없이 간단한 설문 몇 가지 하고 말 것 같기 때문입니다.

만약 높은 보상이지만, 그만큼 너무 많은 설문문항으로 인해 참여도가 낮아진다면, 그것은 설문조사를 만든 그 기획자 잘못이 아닐까요? 저희 서비스는 설문 문항의 수에 따른 불공평한 문제를 해결하거나, 참여를 "독려"할 순 있지만, 결과를 "보장"할 순 없다고 생각합니다.

**Comment by seiwonpark** [comment]
> 설문조사 생성과 참여 시 차감, 획득하는 포인트를 1점으로 할까 합니다.

각 설문조사의 문항과 관련없이 일관되게 포인트를 책정하는 것이야말로 저희 서비스가 해결해야 하는 부분이라 생각합니다. 가령, 모바일 앱에서 '캐시워크'와 같은 서비스를 사용해보신 적 있으신가요? 설치만 하면 되는 간단한 미션일 경우 100포인트라면, 설치 및 가입까지 원하는 경우 200포인트를 지급하는 방식이었고 이게 합당하다고 생각합니다.

설문 문항을 단순히 10개 단위로 나눈다면, 9문항, 19문항, 29문항과 같은 문제는 어떻게 해결할 지 추가적인 이슈가 됩니다. 여기에는 추가적인 알고리즘을 사용하거나, 조금 더 작게 3개 당 0.5포인트와 같이 나누는 것이 더 적절해보입니다.

**Comment by seiwonpark** [comment]
> 번외로 설문당 최대 생성 가능한 질문수와 옵션수는 여유롭게라도 정해 두는 편이 좋을 것 같습니다. 악용할 여지가 있을것 같아요 (혹시 백앤드에서 이미 정해져 있나요?)

[구글 폼](https://support.google.com/docs/answer/7322334?hl=en#:~:text=You%20can%20include%20up%20to,a%20question%20to%20a%20form.)의 경우, 설문 문항과 설문 옵션을 포함해 총 2000개로 제한을 둔다고 합니다. 당연히 제한이 필요할 것 같습니다. (저는 개인적으로 1000개 정도가 적당하다 생각합니다.)

**Comment by seiwonpark** [comment]
> 추가로 질문종류에 따라 참여할때 드는 시간이 다르니 가중치를 다르게 보면 좋을 것 같습니다.
ex) 객관식 : 2pt, 단답형 : 3pt, 주관식 : 5pt
이런식으로 한다면 초기 포인트가 100 정도는 되야 할 것 같습니다.

같은 의견입니다.

**Comment by sanghyun1128** [comment]
> @sanghyun1128 좋은 의견 감사드립니다. 각 말씀하신 것에 대해 질문이 있습니다.
> 
> 1. 좋은 방법이라고 생각합니다! 그런데, "~~~서비스에 불편함을 느끼시는게 있으신가요??" 라는 주관식 답변을 얻기 위해 5포인트를 썼는데
>    "없습니다"와 같은 답변이 대부분이면 .. 이 부분에 대해선 어떻게 생각하신가요??
> 2. 5배는 너무 많지 않을까요..? 즉 하나의 설문조사 생성을 위해 5개의 설문을 참여해야 한다면.. 차라리 2-3배는 어떠실까요??
> 3. 백엔드엔 정해진 것은 없으나, 제한은 둘 수 있습니다. 다만, 프론트에서도 최대 질문 수를 제한하는 것이 가능할까요?? 버튼 비활성화 같은...

1. 장문형 같은경우 간단하게는 최소 글자수, 복잡하게는 성의없는 답변 거르기(NLP?)등 저희가 보완해 주는 방향으로 가는게 좋을것 같고, 지금 존재하는 isRequired 옵션을 작성자가 잘 활용하면 "없습니다" 같은 단순한 답변을 할 이유가 줄어들 것 같습니다.(프론트에서 isRequired 옵션 처리 구현 필요...아직 안되있어요)

2. 초반 이니까 더 낮춰서 1:1 도 괜찮을것 같습니다. 그런데 이 서비스가 많은 사람들에게 이용되는 상황을 가정 했을때, 포인트를 퍼주면 저희가 기프티콘을 그만큼 준비해야 하는 일(돈)이 생기는데 괜찮을까요?

3. 네 가능합니다. 버튼 비활성화하는 방법도 있고, 제출전에 프론트에서도 검사하는 로직이 있습니다(질문이 한개 이상 있는지, 빈칸 있는지 등..) 여기에 추가해도 될거 같아요

**Comment by bezzang-dev** [comment]
세원님 의견 감사드립니다.

> 1. 용어 관련
"데드락"이라는 용어를 두 번이나 말씀하셨는데, 이게 제가 아는 데드락과 무슨 관련이 있는지 잘 모르겠습니다. 단순히 "서로 대기하는 교착 상태"라는 용어에 초점을 맞추신 것이 아닌가 합니다. 저희 서비스가 말씀하신 "데드락"을 발생시킨다면, 기획 자체에 문제가 있는 것입니다. 가령, "누가 돈 내고 000을 쓰냐"와 같은 문제입니다. 단순히 빠르게 설문하고 포인트 얻으려는 설문 참여자 vs 하나의 설문으로 많은 포인트를 얻으려는 설문 생성자 라는 구도라면, 이는 수요와 공급의 문제입니다. 비유는 언제나 비유일 뿐, 의견 개진에는 적합하지 않습니다.

지적 감사합니다. 해당 용어 언급은 수정하도록 하겠습니다.

> 만약 높은 보상이지만, 그만큼 너무 많은 설문문항으로 인해 참여도가 낮아진다면, 그것은 설문조사를 만든 그 기획자 잘못이 아닐까요? 저희 서비스는 설문 문항의 수에 따른 불공평한 문제를 해결하거나, 참여를 "독려"할 순 있지만, 결과를 "보장"할 순 없다고 생각합니다.

동의합니다. 참여도가 낮은 설문조사에 대한 문제 상황을 저희 서비스가 참여도가 높게 하도록 보장하는 것은 어렵다고 생각합니다.

>각 설문조사의 문항과 관련없이 일관되게 포인트를 책정하는 것이야말로 저희 서비스가 해결해야 하는 부분이라 생각합니다. 가령, 모바일 앱에서 '캐시워크'와 같은 서비스를 사용해보신 적 있으신가요? 설치만 하면 되는 간단한 미션일 경우 100포인트라면, 설치 및 가입까지 원하는 경우 200포인트를 지급하는 방식이었고 이게 합당하다고 생각합니다.

서비스가 해결해야 할 부분에 대해 의견 공유해주셔서 감사합니다. 
설문조사 별 적절한 포인트 지급 방식에 대해 더 초점을 두도록 하겠습니다.

**Comment by bezzang-dev** [comment]
상현님 질문에 대답해주셔서 감사합니다. 

> 장문형 같은경우 간단하게는 최소 글자수, 복잡하게는 성의없는 답변 거르기(NLP?)등 저희가 보완해 주는 방향으로 가는게 좋을것 같고, 지금 존재하는 isRequired 옵션을 작성자가 잘 활용하면 "없습니다" 같은 단순한 답변을 할 이유가 줄어들 것 같습니다.(프론트에서 isRequired 옵션 처리 구현 필요...아직 안되있어요) 

해결 방법이 명확한 좋은 답변 감사드립니다!

> 초반 이니까 더 낮춰서 1:1 도 괜찮을것 같습니다. 그런데 이 서비스가 많은 사람들에게 이용되는 상황을 가정 했을때, 포인트를 퍼주면 저희가 기프티콘을 그만큼 준비해야 하는 일(돈)이 생기는데 괜찮을까요?

그것도 맞습니다... 나중에 서비스 인원이 많아진다고 가정하면.... 그제서야 "인원이 너무 많아서 설문조사 생성에 필요한 포인트는 높이고 보상 포인트 낮추겠습니다." 라고 공지하는 것은 좋지 않기 때문에.. 그러면 한 1:2...는 어떨까요

> 네 가능합니다. 버튼 비활성화하는 방법도 있고, 제출전에 프론트에서도 검사하는 로직이 있습니다(질문이 한개 이상 있는지, 빈칸 있는지 등..) 여기에 추가해도 될거 같아요

질문 수 제한을 몇 개 까지 할 것인지도 정해서 반영하면 해결될 것 같습니다!

**Comment by bezzang-dev** [comment]
그럼 총 세 가지 사항으로 제 의견을 정리하자면..

### 포인트 분배 관련
음 질문 종류에 따라 가중치를 둔다면 
저희 서비스 질문 종류가 단일 선택, 복수 선택, 단답형, 주관식 네 가지가 있는데..
단답형이 확실히 제일 낮은 가중치를 두는게 맞다고 생각합니다.

결론은
단답형 -> 1
단일 선택, 복수 선택 -> 2
주관식 -> 3
입니다.

이렇게 되면 설문조사 생성 페이지에서, 총 사용되는 포인트를 계산하는 부분도 추가되면 좋을 것 같습니다.

### 질문 수 제한
이는 저도 1000개면 적당하다고 생각합니다.

### 생성 및 보상 포인트 비율 
1개 설문조사의 생성에 필요한 포인트는 2개의 설문조사를 참여해야 하는건 어떠실까요??
