### ISSUE TITLE
[P0] Query tuning in JPA by separating composite columns

### ISSUE THREAD

**Issue by seiwonpark** [kookmin-sw/capstone-2023-40#44]
See https://www.objectdb.com/java/jpa/entity/id#Embedded_Primary_Key

By separating multiple `@Id` fields we could make better performance when retrieving data from database.

Each entity should have its own primary key and it is ordered in the database. Then, if we make it embeddable, then it'll fetch keys in a continuous order and could make better performance in indexing. Plus, better readability.

But we need to also consider downside of this. In the events like storing data it'll be less efficient because large memory size is required.

For me in this case, I'd like to focus more on fetching data not storing data because of the frequency of both events.

**Comment by SeiwonPark** [comment]
Why not closed???
