### ISSUE TITLE
[P?] Question: Format of error messages from server

### ISSUE THREAD

**Issue by seiwonpark** [kookmin-sw/capstone-2023-40#51]
For error formats sent from server, which do you prefer or think it's right thing to do?

**example 1 (json)**
```json
{
  "status": 404,
  "message": "Page Not Found",
  "some_key": "some_value"
}
```

**example 2 (plain text)**
```text
Page Not Found
```

Both can get status code from client as `error.response`.

I'm... not really sure which would be the right choice... any ideas?

**Comment by bezzang-dev** [comment]
If both can get status code from client.. How about plain text!? It looks simple.

**Comment by sanghyun1128** [comment]
If status code and meesage is enough to handle error, I think ex2 is ok either.

**Comment by ohsung1125** [comment]
I think ex2 looks better from the user's point of view.

**Comment by seiwonpark** [comment]
Closes to have decided to use response as `String` not `Object`.
