### ISSUE TITLE
[P?] How to validate the started and expire date of survey?

### ISSUE THREAD

**Issue by seiwonpark** [kookmin-sw/capstone-2023-40#86]
What do you think is proper way to validate the started and expired date of each survey?

Current:

```java
@NotNull
@FutureOrPresent
@ApiModelProperty(name = "설문조사 시작일", example = "2023-04-01T00:00:00")
private LocalDateTime startedDate;

@NotNull
@Future
@ApiModelProperty(name = "설문조사 종료일", example = "2023-04-08T00:00:00")
private LocalDateTime endedDate;
```

**Comment by bezzang-dev** [comment]
While Java Bean Validation with annotations like `@FutureOrPresent` seems like a good way to validate the started and expired date, there can be **issues** when using it with `LocalTimeDate` type. 

During a test of creating survey, `ConstraintViolationException` occurred when passing the `startedDate` parameter of the `SurveyRequestDto` as `LocalTimeDate.now()`. 
I suspect that this is due to a time difference between the request time and the validation time. 
Then If there is a network delay between the client and server, the client cannot set the `startedDate` time to the present time

As a solution, one could implement the validation in the service layer or consider changing the data type. 
However, I'm not sure which way is better.

**Comment by seiwonpark** [comment]
What a good point! So maybe simply we could allow requests within 5 to 10sec for that API call.

But **fundamental question** here: 
Is it possible to check **Present** then? Although it's as minimum as it could be, but still THERE IS A LATENCY. 

We need to take a look at `@FutureOrPresent` annotation first.

**Comment by bezzang-dev** [comment]
According to the JavaDoc specified in `@FutureOrPresent`, 

_"present" is defined relatively to the type on which the constraint is used. For example, if the constraint is on a Year, "present" would mean the entire current year._

Then, Since @FutureOrPresent annotation determines the point in time of a LocalTimeDate down to the nano-second level, making it impossible to accurately check for the present time...

**Comment by seiwonpark** [comment]
Okay. I guess we've misused types. Do you have any idea on this?

**Comment by bezzang-dev** [comment]
How about using `Date` type instead of `Time`? From the client's point of view, is there a situation where client need to set the exact time to start the survey  time??

**Comment by seiwonpark** [comment]
That's not a reason. Please think again.

**Comment by kimjinmyeong** [comment]
well...
changing the data type or validate at the service layer without using @FutureOrPresent, or not using the startedDate property..?? Do you have any more ideas??

**Comment by bezzang-dev** [comment]
well...
changing the data type or validate at the service layer without using `@FutureOrPresent`, or not using the `startedDate` property..?? Do you have any more ideas??

**Comment by seiwonpark** [comment]
## About the comment
Yes, there're several ways including what you've just said. But be cautious. You **should reason** on your suggestion in order to persuade others.

Especially, `is there a situation where client need to set the exact time to start the survey time??` is the exact kind of groundless thought. What if someone would like to set the starting time of his/her own survey? Could you answer this? Basically to avoid this, you first need to reason on your idea with **fact**.

<br/>   

## Simple but not responsible way
Let's go back to the question, as the `LocalDateTime` with `@FutureOrPresent` validates below seconds level, `LocalDateTime` and annotations with `Present` don't along well actually. (But of course it makes sense when the request could be sent below seconds-level duration. But still it's an ideal case.) So then what should we do?

We could simply use `LocalDate` and do not set any time properties of survey. So it might look as follows:
```java
@NotNull
@FutureOrPresent
@ApiModelProperty(name = "설문조사 시작일", example = "2023-04-01")
private LocalDate startedDate;
```
But this isn't ideal since user cannot set time or minute to start the survey.

<br/>   

## How to solve this issue then?

The reason why I open this issue and asked about how to solve this issue is basically to make you understand the logic and break your mind on validation. 

Seems like you're obsessed with **`annotations`**. Why? Because marking with annotations looks neat, clean, and cool? Why afraid of validating on service layer?(You've mentioned it but without confidence). Actually **validating** doesn't mean `Use validation class of java and put annotation with proper messages on DTO or Domain classes`. Rather it just means `Validate business logics or request object that could be consumed on Server.`.

After all, without or with annotations, you need to validate it on every logic and object. Don't rely on one-way/looks cool/looks simple solutions.

**Comment by bezzang-dev** [comment]
Sometimes when I look at someone else's code, I see code that is more concise, shorter, and better performance than the code I wrote, even if I implemented the same function.

So I think it's a well-organized code, so I tend to be reluctant to complicate or lengthen the code.

After reading your comments, I felt I needed to get rid of this tendency. And I learned some tips to persuade others 
Also, I felt that I had to focus more on the purpose of the code, whether it was a well-written code or not.
Thank you for your comments!

So the way I thought about it is not using `@Future`, `@FutureOrPast` annotation, but validating it in the Service Layer. A 5-second delay between the client-set startedDate time and the server's time allows the client close to start a survey at the `startedDate` time. The server also eliminates the need to change the data type.

And If the `startedDate` is more than 5 seconds past the current time, it is judged as an invalid request.

**Comment by seiwonpark** [comment]
That's good! Make your code works for you, not fit yourself into code.

Likewise `CustomController` is kind of the class I've intended. Since I didn't want to go to `/api/swagger-ui` or `/api/swagger-ui/index.html` but I wanted it to be just simply `/api/docs`.

**Comment by bezzang-dev** [comment]
Okay, I checked it.

**Comment by seiwonpark** [comment]
Closes as it's done.
