### ISSUE TITLE
[P0] Idempotency, is it right?

### ISSUE THREAD

**Issue by seiwonpark** [kookmin-sw/capstone-2023-40#94]
Regarding #93, we should modify our `PUT` requests to `PATCH`. This seems more logical if you see our service layer methods.

At first I've insisted on `IDEMPOTENCY`, but I don't think this efficient nor logical.

`PUT`: Actually **replaces** resource with its full contents. Ideally this should be used on situations where we need to modify the whole part. But we're not.

So, `PATCH` seems better since it only updates parts of the resource. And much logical.

**Comment by bezzang-dev** [comment]
I agree with you.
the server don't need to perform a full update of the resource at the request of the client.
